"""
PPPoE Connection Manager
Quản lý kết nối PPPoE: connect, disconnect, reconnect để xoay IP động.
"""

import subprocess
import time
import re
import json
import logging
import os
import signal

logger = logging.getLogger("pppoe_manager")


class PPPoEManager:
    """Quản lý kết nối PPPoE để xoay IP động."""

    PEER_NAME = "nest_provider"
    PEER_FILE = f"/etc/ppp/peers/{PEER_NAME}"
    PPP_INTERFACE = "ppp0"

    def __init__(self, config_path: str = "config.json"):
        with open(config_path, "r") as f:
            self.config = json.load(f)

        pppoe = self.config["pppoe"]
        self.username = pppoe["username"]
        self.password = pppoe["password"]
        self.interface = pppoe.get("interface", "eth0")
        self.provider = pppoe.get("provider", "UNKNOWN")
        self.device_code = self.config.get("device_code", "UNKNOWN")

        self._current_ip = None
        self._setup_peer()

    def _setup_peer(self):
        """Tạo file cấu hình PPPoE peer cho pppd."""
        peer_content = f"""# Auto-generated by nest PPPoE Manager
# Provider: {self.provider}
# Device: {self.device_code}

plugin rp-pppoe.so
nic-{self.interface}

user "{self.username}"

noipdefault
defaultroute
replacedefaultroute
hide-password
noauth
persist
maxfail 3
holdoff 5

mtu 1492
mru 1492

lcp-echo-interval 20
lcp-echo-failure 3

usepeerdns
"""
        # Ghi peer file
        with open(self.PEER_FILE, "w") as f:
            f.write(peer_content)
        logger.info(f"Đã tạo peer file: {self.PEER_FILE}")

        # Ghi credentials vào chap-secrets và pap-secrets
        cred_line = f'"{self.username}" * "{self.password}" *\n'
        for secret_file in ["/etc/ppp/chap-secrets", "/etc/ppp/pap-secrets"]:
            # Đọc file hiện tại, xóa dòng cũ nếu có
            lines = []
            if os.path.exists(secret_file):
                with open(secret_file, "r") as f:
                    lines = [
                        l
                        for l in f.readlines()
                        if self.username not in l
                    ]
            lines.append(cred_line)
            with open(secret_file, "w") as f:
                f.writelines(lines)
            os.chmod(secret_file, 0o600)

        logger.info(f"Đã cấu hình credentials cho {self.username}")

    def connect(self, timeout: int = 30) -> str | None:
        """Kết nối PPPoE, trả về IP mới hoặc None nếu thất bại."""
        logger.info(f"Đang kết nối PPPoE qua {self.interface}...")

        # Chạy pon
        result = subprocess.run(
            ["pon", self.PEER_NAME],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode != 0:
            logger.error(f"pon thất bại: {result.stderr}")
            return None

        # Đợi interface ppp0 lên và nhận IP
        ip = self._wait_for_ip(timeout)
        if ip:
            self._current_ip = ip
            logger.info(f"✅ Kết nối thành công! IP: {ip}")
        else:
            logger.error("❌ Không nhận được IP sau khi kết nối")
        return ip

    def disconnect(self) -> bool:
        """Ngắt kết nối PPPoE."""
        logger.info("Đang ngắt kết nối PPPoE...")

        # Thử poff trước
        result = subprocess.run(
            ["poff", self.PEER_NAME],
            capture_output=True,
            text=True,
            timeout=10,
        )

        # Kill pppd nếu vẫn còn chạy
        try:
            subprocess.run(
                ["pkill", "-TERM", "pppd"],
                capture_output=True,
                timeout=5,
            )
        except Exception:
            pass

        # Đợi interface ppp0 mất
        for _ in range(10):
            if not self._is_ppp_up():
                self._current_ip = None
                logger.info("✅ Đã ngắt kết nối PPPoE")
                return True
            time.sleep(1)

        # Force kill
        try:
            subprocess.run(
                ["pkill", "-9", "pppd"],
                capture_output=True,
                timeout=5,
            )
            time.sleep(2)
        except Exception:
            pass

        self._current_ip = None
        logger.info("✅ Đã force ngắt kết nối PPPoE")
        return True

    def reconnect(self, delay: float = 3.0, timeout: int = 30) -> str | None:
        """
        Ngắt kết nối rồi kết nối lại để lấy IP mới.
        delay: thời gian chờ giữa disconnect và connect (giây)
        """
        old_ip = self._current_ip
        logger.info(f"🔄 Xoay IP... (IP cũ: {old_ip})")

        self.disconnect()
        time.sleep(delay)
        new_ip = self.connect(timeout)

        if new_ip and new_ip != old_ip:
            logger.info(f"🎉 Đã xoay IP: {old_ip} → {new_ip}")
        elif new_ip == old_ip:
            logger.warning(f"⚠️  IP không đổi: {new_ip}")
        else:
            logger.error("❌ Xoay IP thất bại")

        return new_ip

    def get_current_ip(self) -> str | None:
        """Lấy IP hiện tại của interface PPP."""
        try:
            result = subprocess.run(
                ["ip", "-4", "addr", "show", self.PPP_INTERFACE],
                capture_output=True,
                text=True,
                timeout=5,
            )
            match = re.search(r"inet (\d+\.\d+\.\d+\.\d+)", result.stdout)
            if match:
                self._current_ip = match.group(1)
                return self._current_ip
        except Exception as e:
            logger.debug(f"Không lấy được IP: {e}")
        return None

    def get_public_ip(self) -> str | None:
        """Lấy public IP qua HTTP request."""
        import urllib.request

        services = [
            "https://api.ipify.org",
            "https://ifconfig.me/ip",
            "https://icanhazip.com",
        ]
        for url in services:
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "curl/7.68"})
                with urllib.request.urlopen(req, timeout=10) as resp:
                    ip = resp.read().decode().strip()
                    if re.match(r"^\d+\.\d+\.\d+\.\d+$", ip):
                        return ip
            except Exception:
                continue
        return None

    def status(self) -> dict:
        """Trả về trạng thái kết nối hiện tại."""
        is_up = self._is_ppp_up()
        ppp_ip = self.get_current_ip() if is_up else None
        public_ip = self.get_public_ip() if is_up else None

        return {
            "connected": is_up,
            "ppp_interface": self.PPP_INTERFACE,
            "ppp_ip": ppp_ip,
            "public_ip": public_ip,
            "provider": self.provider,
            "device_code": self.device_code,
            "eth_interface": self.interface,
        }

    def _is_ppp_up(self) -> bool:
        """Kiểm tra interface ppp0 có UP không."""
        try:
            result = subprocess.run(
                ["ip", "link", "show", self.PPP_INTERFACE],
                capture_output=True,
                text=True,
                timeout=5,
            )
            return "UP" in result.stdout and result.returncode == 0
        except Exception:
            return False

    def _wait_for_ip(self, timeout: int = 30) -> str | None:
        """Đợi cho đến khi nhận được IP trên ppp0."""
        start = time.time()
        while time.time() - start < timeout:
            ip = self.get_current_ip()
            if ip:
                return ip
            time.sleep(1)
        return None
